FROM hwnam831/gnn-training

WORKDIR /home/benchmarking-gnns
COPY collab-graphsage.json /home/benchmarking-gnns/
COPY CSL-gcn.json /home/benchmarking-gnns/
COPY superpixels_gat_cifar10.json /home/benchmarking-gnns/
COPY run_model.py /home/benchmarking-gnns/
ENTRYPOINT ["bash"]